/*
* MIT License
* 
* Copyright (c) 2015 - present valda-z
* 
* All rights reserved.
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in all
* copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NonProfitCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.CompanySub = new HashSet<CompanySub>();
            this.Event = new HashSet<Event>();
            this.Tag2Company = new HashSet<Tag2Company>();
        }
    
        public int Id { get; set; }
        public int StatusId { get; set; }
        public string Name { get; set; }
        public string IdentificationNumber { get; set; }
        public string Contact1Name { get; set; }
        public string Contact1Phone { get; set; }
        public string Contact1Email { get; set; }
        public string Contact1Note { get; set; }
        public string Contact2Name { get; set; }
        public string Contact2Phone { get; set; }
        public string Contact2Email { get; set; }
        public string Contact2Note { get; set; }
        public string Www { get; set; }
        public int CountryId { get; set; }
        public int RegionId { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Note { get; set; }
        public bool Deleted { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Region Region { get; set; }
        public virtual CompanyStatus CompanyStatus { get; set; }
        public virtual ICollection<CompanySub> CompanySub { get; set; }
        public virtual ICollection<Event> Event { get; set; }
        public virtual ICollection<Tag2Company> Tag2Company { get; set; }
    }
}
