//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NonProfitCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanySub
    {
        public CompanySub()
        {
            this.Event2CompanySub = new HashSet<Event2CompanySub>();
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public int CountryId { get; set; }
        public int RegionId { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Note { get; set; }
        public bool Deleted { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Country Country { get; set; }
        public virtual Region Region { get; set; }
        public virtual ICollection<Event2CompanySub> Event2CompanySub { get; set; }
    }
}
