//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NonProfitCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public System.DateTime Created { get; set; }
        public string LogType { get; set; }
        public string Description { get; set; }
        public string Data { get; set; }
        public string Entity { get; set; }
        public Nullable<int> EntityID { get; set; }
    }
}
