//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NonProfitCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonProfitOrgType
    {
        public NonProfitOrgType()
        {
            this.NonProfitOrg = new HashSet<NonProfitOrg>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<NonProfitOrg> NonProfitOrg { get; set; }
    }
}
