//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NonProfitCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.Company = new HashSet<Company>();
            this.CompanySub = new HashSet<CompanySub>();
            this.NonProfitOrg = new HashSet<NonProfitOrg>();
        }
    
        public int Id { get; set; }
        public int CountryId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Company> Company { get; set; }
        public virtual ICollection<CompanySub> CompanySub { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<NonProfitOrg> NonProfitOrg { get; set; }
    }
}
