//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NonProfitCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.Tag2Company = new HashSet<Tag2Company>();
            this.Tag2Event = new HashSet<Tag2Event>();
            this.Tag2NonProfitOrg = new HashSet<Tag2NonProfitOrg>();
        }
    
        public int Id { get; set; }
        public string Tag1 { get; set; }
    
        public virtual ICollection<Tag2Company> Tag2Company { get; set; }
        public virtual ICollection<Tag2Event> Tag2Event { get; set; }
        public virtual ICollection<Tag2NonProfitOrg> Tag2NonProfitOrg { get; set; }
    }
}
