//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NonProfitCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEventList
    {
        public int Id { get; set; }
        public System.DateTime DateOfEvent { get; set; }
        public int Capacity { get; set; }
        public string Name { get; set; }
        public string ContactCompanyName { get; set; }
        public string ContactCompanyPhone { get; set; }
        public string ContactCompanyEmail { get; set; }
        public string ContactNonProfitOrgName { get; set; }
        public string ContactNonProfitOrgPhone { get; set; }
        public string ContactNonProfitOrgEmail { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime Updated { get; set; }
        public string UpdatedBy { get; set; }
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public int NonProfitOrgId { get; set; }
        public string NonProfitOrgName { get; set; }
        public Nullable<System.DateTime> Closed { get; set; }
        public bool Insurance { get; set; }
    }
}
